targets:
  $default:
    builders:
      swagger_dart_code_generator:
        options:
          input_folder: 'lib/networkLib/swagger'
          output_folder: 'lib/networkLib/cairoApi/'
          override_equals_and_hashcode: true
          build_only_models: true