enum DataManagerAction {
  
  ERR_ACTION_REQUIRE_LOGON,
  ERR_ACTION_REQUIRE_REINSTALL_APP,
  ERR_ACTION_REQUIRE_CHANGE_USER_OR_REINSTALL_APP,
  ERR_ACTION_REQUIRE_CONFIRM_CHANGE_DEVICE,
  ERR_ACTION_REQUIRE_UPGRADE_APP,
  ERR_ACTION_REQUIRE_RESTART_APP,
  ERR_ACTION_RETRY_LATER,
  WARN_ACTION_COMPLETE_PROFILE,
  WARN_ACTION_CONTINUE_WITH_CACHED_DATA,
  ERR_ACTION_SEND_ERROR_TO_ADMIN,
}
